---

- name: 'manage lxd installation and mysql-server container'
  hosts: 'target'
  gather_facts: no
  roles:
    - lxd
  tasks:
    - name: 'manage mysql-server container'
      lxd_container:
        name: mysql-server
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/xenial/amd64
        timeout: 60
        wait_for_ipv4_addresses: true
      register: container
    - name: 'internal configuration'
      set_fact:
        mysql: "{{ container.addresses.eth0 | first }}"

- name: 'manage mysql-server installation'
  hosts: 'mysql-server'
  gather_facts: no
  vars:
    mysqld:
      databases:
        - 'laravel'
      users:
        - name: 'laravel'
          host: '%'
          database: 'laravel'
  roles:
    - mysqld
  pre_tasks:
    - name: 'check python'
      raw: 'dpkg -s python'
      register: cmd
      failed_when: no
      changed_when: no
    - name: 'install python'
      raw: apt-get install -y python
      when: cmd.rc == 1

- name: 'manage docker and project installation'
  hosts: 'target'
  roles:
    - docker
    - role: project
      vars:
        project:
          mysql:
            host: '{{ mysql }}'
            username: 'laravel'
            database: 'laravel'
      tags:
        - deploy
