---

driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: deploy.yml
  hosts: hosts
  roles_path: roles
  ansible_verbose: true
  require_chef_for_busser: false

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
